foreground            #C5C8C6
background            #00141A

cursor                #B58900
cursor_text_color     #00141A

selection_foreground  #00141A
selection_background  #93A1A1

url_color             #268BD2

# Black
color0   #073642
color8   #586E75

# Red
color1   #DC322F
color9   #FF6B68

# Green
color2   #859900
color10  #B4C342

# Yellow
color3   #B58900
color11  #E1AF4B

# Blue
color4   #268BD2
color12  #5FA8FF

# Magenta
color5   #D33682
color13  #FF79C6

# Cyan
color6   #2AA198
color14  #5FD7D7

# White
color7   #EEE8D5
color15  #FDF6E3
