# Start window numbering at 1
set -g base-index 1

set -ga terminal-overrides ',xterm-kitty:RGB' 
set -g default-terminal "xterm-kitty"
set-option -sa terminal-overrides ",xterm*:Tc"
# set -g default-terminal "tmux-256color"
# set -g default-terminal "xterm-256color"
# set -ga terminal-overrides ",*256col*:Tc"
# set -ga terminal-overrides ",xterm-256color:Tc"
set -g mouse on
set -g set-clipboard on
set -g base-index 1
set -g pane-base-index 1
#some keybinds

set -g @dracula-transparent-powerline-bg true
#lazygit
bind -r g display-popup -d '#{pane_current_path}' -w80% -h80% -E 'lazygit'

unbind r
bind r source-file ~/.config/tmux/tmux.conf
unbind v
bind v copy-mode

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

bind -r m resize-pane -Z

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R


bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

# Start pane numbering at 1
set -g pane-base-index 1

# Renumber windows after closing
set -g renumber-windows on
# status bar
set -g status-style bg=default

# inactive window
set-window-option -g window-status-style fg=colour245,bg=default

# active window
set-window-option -g window-status-current-style fg=colour111,bg=default,bright

# pane borders
set-option -g pane-border-style fg=colour238
set-option -g pane-active-border-style fg=colour111

# message text
set-option -g message-style bg=colour111,fg=colour235

# pane number display
set-option -g display-panes-active-colour colour204
set-option -g display-panes-colour colour149

# clock
#set-window-option -g clock-mode-colour colour141

set -g status-justify "left"


