# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=#f5fafd

# Main text color
theme[main_fg]=#171c1f

# Title color for boxes
theme[title]=#171c1f

# Highlight color for keyboard shortcuts
theme[hi_fg]=#08677f

# Background color of selected item in processes box
theme[selected_bg]=#eaeff2

# Foreground color of selected item in processes box
theme[selected_fg]=#08677f

# Color of inactive/disabled text
theme[inactive_fg]=#6d767a

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]=#717295

# Background color of the percentage meters
theme[meter_bg]=#6d767a

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]=#717295

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]=#005a81
theme[mem_box]=#007b86
theme[net_box]=#2751f9
theme[proc_box]=#006182

# Box divider line and small boxes line color
theme[div_line]=#bfc8cc

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]=#007b86
theme[temp_mid]=#008f68
theme[temp_end]=#003ee0

# CPU graph colors (Teal -> Sapphire -> Lavender)
theme[cpu_start]=#007289
theme[cpu_mid]=#007d98
theme[cpu_end]=#007aa5

# Mem/Disk free meter (Mauve -> Lavender -> Blue)
theme[free_start]=#005a81
theme[free_mid]=#007aa5
theme[free_end]=#006182

# Mem/Disk cached meter (Sapphire -> Blue -> Lavender)
theme[cached_start]=#007d98
theme[cached_mid]=#006182
theme[cached_end]=#007aa5

# Mem/Disk available meter (Peach -> Maroon -> Red)
theme[available_start]=#8a4dff
theme[available_mid]=#2751f9
theme[available_end]=#003ee0

# Mem/Disk used meter (Green -> Teal -> Sky)
theme[used_start]=#007b86
theme[used_mid]=#007289
theme[used_end]=#0084a7

# Download graph colors (Peach -> Maroon -> Red)
theme[download_start]=#8a4dff
theme[download_mid]=#2751f9
theme[download_end]=#003ee0

# Upload graph colors (Green -> Teal -> Sky)
theme[upload_start]=#007b86
theme[upload_mid]=#007289
theme[upload_end]=#0084a7

# Process box color gradient for threads, mem and cpu usage (Sapphire -> Lavender -> Mauve)
theme[process_start]=#007d98
theme[process_mid]=#007aa5
theme[process_end]=#005a81
